name: rajesh_tyres_inventory
description: A tyre inventory management system for Rajesh Tyres & Co.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  responsive_framework: ^1.3.0
  google_fonts: ^6.1.0
  data_table_2: ^2.5.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.4.5
  js: ^0.7.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/ 